---
title: "Assignment4-Group3"
author: "Group3"
date: "03/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
```


# Diyao Chen: 
1. Which genre are highest rated?
2. Which genre support most languages?
3. Which genre support most devices?

# Sen Wang: 

```{r}
data <- read_csv(here::here("data", "AppleStore.csv"))
```

```{r tidy-data}
data2 <- data %>%
  filter(rating_count_tot > 100) %>%
  mutate(size_mb = size_bytes/1024/1024)
```

1. Genre-rating-price correlation?

```{r data_plot1, fig.cap="No strong relation between app categories and user ratings in different price", message=FALSE, warning=FALSE, fig.width=12, fig.height=12}
# A histogram showing the relation between app categories and user ratings in different price.
data2 %>%
  ggplot(aes(x = prime_genre,
             y = user_rating,
             fill = prime_genre)) +
  geom_histogram(stat = 'summary',
                 fun.y = mean,
                 show.legend = FALSE) +
  coord_flip() +
  labs (x = "Categories", 
        y = "Average of user rating",
        title = "No strong relation between app categories and user ratings in different price") +
  facet_wrap(~price) +
  theme_minimal()
```

2. Genre-rating-size correlation?

# Yezi He:
1. Most number of rating counts for which apps/genre? (i.e., number of people who rated)
2. Rise/drop in rating since last update?

# Ketan Kabu:
1. Development-Rating correlation?